### ISSUE TITLE
Usage with Typescript

### ISSUE THREAD

**Issue by jsonmaur** [jfgodoy/knex-postgis#35] opened 2019-10-23 00:23 UTC
Can't seem to use this library with Typescript cause it looks like the DefinitelyTyped definitions are out of date (don't know if you maintain those or not): https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/knex-postgis

For reference, this is the type error:
```
Argument of type 'Knex<any, unknown[]>' is not assignable to parameter of type 'Knex'.
  Property 'clone' is missing in type 'Knex<any, unknown[]>' but required in type 'Knex'.
```

Usage:
```
const db = knex({ dialect: "postgres" })
const st = knexPostgis(db)
```

**Comment by jfgodoy** [comment] 2019-10-23 01:18
hi @jsonmaur, 
sorry, I don't mantain that project and I haven't used typescript to be of any help.

I you need to make a PR  to this project to fix the issue I'll be happy to review.

**Comment by ctusch** [comment] 2019-10-23 15:58
Funnily I ran into the exact same problem yesterday too. The problem is that `@types/knex-postgis` comes with its own `knex` dependency locked at `^0.16.1`. Since `knex` is still doing 0.x releases that means `npm install` won't install `0.17.0` or higher but instead `@types/knex-postgis` gets its own local `knex` dependency whose typings are outdated compared to the newer `knex` typings which get passed to the `KnexPostgis` function.

Possible workarounds without updating the typings (which are missing the function definitions mentioned in the change log but which I don't need):
- cast `db` to `any`
- force `@types/knex-postgis` to use a newer version of `knex` via `yarn`'s selective dependency resolutions (or maybe `npm-force-resolutions` for `npm`)
- install `knex` version `0.16.3` so the typings match

**Comment by jfgodoy** [comment] 2019-11-12 11:27
hi guys, I created a pull request #37 that adds basic support for typescript. To my understanding this will fix this issue. I would like you to review this PR and comment it if it is good enough before merge.
You have more experience working with typescript so I would thank you if you can help me to improve the solution.

**Comment by ctusch** [comment] 2019-11-12 13:18
Thank you! I'll have a look at it.

**Comment by jfgodoy** [comment] 2019-11-15 23:41
I just publish v0.10.0 which includes basic support for typescript. I will close this issue for now, but feel free to open it if you have any problem with the new release.

**Closed by jfgodoy** 2019-11-15 23:41 UTC

**Comment by AbdelIdir** [comment] 2020-12-17 14:54
I'm currently dealing with the same issue, attempting to use Knex-cleaner to truncate before each test:

node: 12.13.1
knex: ^0.21.13
knex-cleaner: ^1.3.1




```
import knexCleaner from "knex-cleaner";
import knex from ".././config/db-config";


type Options = {
      mode: string;
      restartIdentity: boolean;
      ignoreTables?: string[];
};
beforeEach(() => {
      const options: Options = {
            mode: "truncate", // Valid options 'truncate', 'delete'
            restartIdentity: true // Used to tell PostgresSQL to reset the ID counter
            // ignoreTables: ["Dont_Del_1", "Dont_Del_2"]
      };
      return knexCleaner.clean(knex, options).then(function () {
            console.log("the database is now clean");
      });
});
```

Getting the error :

```
Argument of type 'Knex<any, unknown[]>' is not assignable to parameter of type 'Knex'.
  Property 'clone' is missing in type 'Knex<any, unknown[]>' but required in type 'Knex'.ts(2345)
knex.d.ts(216, 5): 'clone' is declared here.
```
